export const fieldConfigurations = {
  id: { label: "id", type: "number" },
  statusId: { label: "id", type: "number" },
  totalEmployees: { label: "Tổng số lao động", type: "number" },
  femaleEmployees: { label: "Lao động nữ", type: "number" },
  employeesUnder15: { label: "Lao động dưới 15 tuổi", type: "number" },
  hazardousWorkers: { label: "Lao động làm công tác ATLĐ", type: "number" },
  hazardousEmployees: { label: "Lao động làm việc trong điều kiện độc hại", type: "number" },
  disabledEmployees: { label: "Lao động người khuyết tật", type: "number" },
  healthcareWorkers: { label: "Người làm công tác y tế", type: "number" },
  underageEmployees: { label: "Lao động là người chưa thành niên", type: "number" },
  elderlyEmployees: { label: "Lao động người cao tuổi", type: "number" },
  totalAccidents: { label: "Tổng số vụ TNLĐ", type: "number" },
  fatalities: { label: "Số vụ có người chết", type: "number" },
  fatalAccidents: { label: "Số người chết vì TNLĐ", type: "number" },
  totalAccidentCosts: { label: "Tổng chi phí cho TNLĐ", type: "number" },
  injuredEmployees: { label: "Số người bị TNLĐ", type: "number" },
  lostWorkDays: { label: "Số ngày công bị TNLĐ", type: "number" },
  affectedEmployees: { label: "Tổng số người bị BNN tới thời điểm BC", type: "number" },
  earlyRetirements: { label: "Số người nghỉ trước tuổi hưu vì BNN", type: "number" },
  newCases: { label: "Số người mắc mới BNN", type: "number" },
  totalCosts: { label: "Tổng chi phí BNN phát sinh trong năm", type: "money" },
  sickLeaveDays: { label: "Số ngày công nghỉ phép vì BNN", type: "number" },
  healthCategory1: { label: "Loại I (Người)", type: "number" },
  healthCategory2: { label: "Loại II (Người)", type: "number" },
  healthCategory3: { label: "Loại III (Người)", type: "number" },
  healthCategory4: { label: "Loại IV (Người)", type: "number" },
  healthCategory5: { label: "Loại V (Người)", type: "number" },
  group1TrainingCount: { label: "Nhóm 1: SL huấn luyện/SL hiện có (Người/Người)", type: "slash", prefix: "0", suffix: "0" },
  selfTraining: { label: "Trong đó: Tự huấn luyện", type: "slash", prefix: "0", suffix: "0" },
  group2TrainingCount: { label: "Nhóm 2: SL huấn luyện/SL hiện có (Người/Người)", type: "slash", prefix: "0", suffix: "0" },
  outsourcedTraining: { label: "Trong đó: Thuê tổ chức cung cấp dịch vụ huấn luyện", type: "slash", prefix: "0", suffix: "0" },
  group3TrainingCount: { label: "Nhóm 3: SL huấn luyện/SL hiện có (Người/Người)", type: "slash", prefix: "0", suffix: "0" },
  group4TrainingCount: { label: "Nhóm 4: SL huấn luyện/SL hiện có (Người/Người)", type: "slash", prefix: "0", suffix: "0" },
  group5TrainingCount: { label: "Nhóm 5: SL huấn luyện/SL hiện có (Người/Người)", type: "slash", prefix: "0", suffix: "0" },
  group6TrainingCount: { label: "Nhóm 6: SL huấn luyện/SL hiện có (Người/Người)", type: "slash", prefix: "0", suffix: "0" },
  totalTrainingCosts: { label: "Tổng chi phí huấn luyện", type: "money" },
  totalEquipment: { label: "Tổng số", type: "number" },
  uninspectedEquipment: { label: "Số chưa được kiểm định", type: "number" },
  strictEquipment: { label: "Máy có yêu cầu nghiêm ngặt về ATVSLĐ đang sử dụng", type: "number" },
  inspectedEquipment: { label: "Số đã được kiểm định", type: "number" },
  unreportedEquipment: { label: "Số chưa được khai báo", type: "number" },
  reportedEquipment: { label: "Số đã được khai báo", type: "number" },
  totalOvertimeEmployees: { label: "Số người làm thêm trong năm (người)", type: "number" },
  totalOvertimeHours: { label: "Tổng số giờ làm thêm trong năm (người)", type: "number" },
  maxOvertimeHoursPerMonth: { label: "Số giờ làm thêm cao nhất trong 1 tháng (người)", type: "number" },
  totalBeneficiaries: { label: "Tổng số người", type: "number" },
  totalAllowanceCosts: { label: "Tổng chi phí quy định tại điểm 10", type: "money" },
  totalMonitoringSamples: { label: "Số mẫu quan trắc môi trường lao động (Mẫu)", type: "number" },
  nonCompliantSamples: { label: "Số mẫu không đạt tiêu chuẩn (Mẫu)", type: "number" },
  nonCompliantTemperatureSamples: { label: "Mẫu nhiệt độ không đạt (Mẫu/Mẫu)", type: "slash" },
  nonCompliantLightSamples: { label: "Mẫu ánh sáng không đạt (Mẫu/Mẫu)", type: "slash" },
  nonCompliantVibrationSamples: { label: "Mẫu rung không đạt (Mẫu/Mẫu)", type: "slash" },
  nonCompliantEMFSamples: { label: "Mẫu điện từ trường không đạt (Mẫu/Mẫu)", type: "slash" },
  nonCompliantHumiditySamples: { label: "Mẫu độ ẩm không đạt (Mẫu/Mẫu)", type: "slash" },
  nonCompliantNoiseSamples: { label: "Mẫu tiếng ồn không đạt (Mẫu/Mẫu)", type: "slash" },
  nonCompliantToxicGasSamples: { label: "Mẫu hơi khí độc không đạt (Mẫu/Mẫu)", type: "slash" },
  nonCompliantOtherSamples: { label: "Mẫu khác không đạt (Mẫu/Mẫu)", type: "slash" },
  nonCompliantWindSpeedSamples: { label: "Mẫu tốc độ gió không đạt (Mẫu/Mẫu)", type: "slash" },
  nonCompliantDustSamples: { label: "Mẫu bụi không đạt (Mẫu/Mẫu)", type: "slash" },
  nonCompliantRadiationSamples: { label: "Mẫu phóng xạ không đạt (Mẫu/Mẫu)", type: "slash" },
  safetyMeasuresCosts: { label: "Các biện pháp kỹ thuật an toàn", type: "money" },
  hygieneMeasuresCosts: { label: "Các biện pháp kỹ thuật vệ sinh", type: "money" },
  ppeCosts: { label: "Trang bị phương tiện bảo vệ cá nhân", type: "money" },
  trainingCosts: { label: "Tuyên truyền huấn luyện", type: "money" },
  employeeHealthcareCosts: { label: "Chăm sóc sức khỏe người lao động", type: "money" },
  riskAssessmentCosts: { label: "Đánh giá nguy cơ rủi ro về ATVSLĐ", type: "money" },
  otherCosts: { label: "Chi khác", type: "money" },
  safetyServiceProvider: { label: "Tên tổ chức dịch vụ ATVSLĐ được thuê", type: "number" },
  healthServiceProvider: { label: "Tên tổ chức dịch vụ vệ sinh được thuê", type: "number" },
  evaluationDate: { label: "Ngày", type: "date" }
};
